// Code generated by Drift plugin pipeline. DO NOT EDIT.

import UIKit

enum DriftPluginRegistrant {
    static func registerAll(host: DriftPluginHost) {
    }

    static func didFinishLaunching(
        application: UIApplication,
        launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) {
        NotificationHandler.start()
    }

    static func openURL(_ url: URL, source: String) {
        DeepLinkHandler.handle(url: url, source: source)
    }

    static func continueUserActivity(_ userActivity: NSUserActivity, source: String) {
        if let url = userActivity.webpageURL {
            DeepLinkHandler.handle(url: url, source: source)
        }
    }

    static func didRegisterForRemoteNotifications(
        application: UIApplication,
        deviceToken: Data
    ) {
        NotificationHandler.handleDeviceToken(deviceToken)
    }

    static func didFailToRegisterForRemoteNotifications(
        application: UIApplication,
        error: Error
    ) {
        NotificationHandler.handleRemoteNotificationError(error)
    }

    static func didReceiveRemoteNotification(
        application: UIApplication,
        userInfo: [AnyHashable: Any],
        completionHandler: @escaping (UIBackgroundFetchResult) -> Void
    ) {
        NotificationHandler.handleRemoteNotification(userInfo, isForeground: application.applicationState == .active)
        let handlers: [DriftPluginCoordinator.BackgroundFetchHandler] = []
        DriftPluginCoordinator.dispatchBackgroundFetch(
            userInfo: userInfo,
            handlers: handlers,
            completionHandler: completionHandler
        )
    }
}
