// Code generated by Drift plugin pipeline. DO NOT EDIT.

enum DriftPluginRegistrant {
    /// Creates one instance of every configured plugin, in drift.yaml order.
    static func makePlugins() -> [DriftPlugin] {
        return []
    }
}
