//go:build drift_tool

// Code generated by drift CLI from drift.yaml. DO NOT EDIT.
// Regenerated by drift build/run/plugin sync.

package main

import (
	driftplugin "github.com/go-drift/drift/pkg/plugin"

	splash "github.com/go-drift/drift/plugins/splash/plugin"
)

func main() {
	driftplugin.Main(
		driftplugin.Bind("github.com/go-drift/drift/plugins/splash/plugin", splash.Plugin),
	)
}
