package plugin

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-drift/drift/cmd/drift/internal/plugin/mutate"
	"github.com/go-drift/drift/cmd/drift/internal/templates"
	"github.com/go-drift/drift/pkg/plugin/protocol"
)

// AndroidRunnerSupportFiles names the templates that EnsureRunnerSupport
// writes into an ejected Android project's `com.drift.runner` package: the
// plugin API and the plugin lifecycle owner. They are the exact same bytes
// scaffold.WriteAndroid copies during a fresh scaffold; keeping a single
// source of truth here prevents drift between the two. (Earlier the two
// surfaces carried duplicated Kotlin source and the MethodHandler signature
// drifted, breaking every Android build that re-applied EnsureRunnerSupport
// after scaffold.)
var AndroidRunnerSupportFiles = []struct {
	Name         string
	TemplatePath string
}{
	{"DriftPluginHost.kt", "android/runner/DriftPluginHost.kt"},
	{"DriftPlugin.kt", "android/runner/DriftPlugin.kt"},
	{"DriftActivityBinding.kt", "android/runner/DriftActivityBinding.kt"},
	{"DriftPlugins.kt", "android/runner/DriftPlugins.kt"},
	{"DriftMethodHandler.kt", "android/runner/DriftMethodHandler.kt"},
}

// WriteRegistrant generates DriftPluginRegistrant for the target platform and
// writes it into buildDir at the fixed runtime-runner path. It only lists
// the configured plugin classes, in drift.yaml order; the hand-written
// DriftPlugins support file drives their lifecycle and the app templates
// keep Drift's own event handling. With no plugins the list is empty, so
// the call site always resolves.
func WriteRegistrant(buildDir, platform string, ops []protocol.Op) ([]string, error) {
	switch platform {
	case "android":
		dest := filepath.Join(buildDir, "app", "src", "main", "java", "com", "drift", "runner", "DriftPluginRegistrant.kt")
		return writeIfDifferentSingle(dest, []byte(androidRegistrant(ops)))
	case "ios", "xtool":
		dest := filepath.Join(iosRunnerSourcesDir(buildDir, platform), "DriftPluginRegistrant.swift")
		return writeIfDifferentSingle(dest, []byte(iosRegistrant(ops)))
	default:
		return nil, fmt.Errorf("WriteRegistrant: unknown platform %q", platform)
	}
}

func androidRegistrant(ops []protocol.Op) string {
	var b strings.Builder
	b.WriteString("// Code generated by Drift plugin pipeline. DO NOT EDIT.\n")
	b.WriteString("package com.drift.runner\n\n")
	b.WriteString("object DriftPluginRegistrant {\n")
	b.WriteString("    /** Creates one instance of every configured plugin, in drift.yaml order. */\n")
	b.WriteString("    fun makePlugins(): List<DriftPlugin> = listOf(\n")
	for _, op := range ops {
		if p, ok := op.(*protocol.OpAndroidPlugin); ok {
			fmt.Fprintf(&b, "        %s(),\n", p.Class)
		}
	}
	b.WriteString("    )\n")
	b.WriteString("}\n")
	return b.String()
}

func iosRegistrant(ops []protocol.Op) string {
	var plugins []*protocol.OpIOSPlugin
	for _, op := range ops {
		if p, ok := op.(*protocol.OpIOSPlugin); ok {
			plugins = append(plugins, p)
		}
	}
	var b strings.Builder
	b.WriteString("// Code generated by Drift plugin pipeline. DO NOT EDIT.\n\n")
	b.WriteString("import DriftPluginAPI\n")
	imported := map[string]bool{}
	for _, p := range plugins {
		if module := mutate.PluginModule(p.PluginID()); !imported[module] {
			imported[module] = true
			fmt.Fprintf(&b, "import %s\n", module)
		}
	}
	b.WriteString("\nenum DriftPluginRegistrant {\n")
	b.WriteString("    /// Creates one instance of every configured plugin, in drift.yaml order.\n")
	b.WriteString("    static func makePlugins() -> [DriftPlugin] {\n")
	if len(plugins) == 0 {
		b.WriteString("        return []\n")
	} else {
		b.WriteString("        return [\n")
		for _, p := range plugins {
			fmt.Fprintf(&b, "            %s.%s(),\n", mutate.PluginModule(p.PluginID()), p.Class)
		}
		b.WriteString("        ]\n")
	}
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

// EnsureRunnerSupport writes the Drift-owned plugin support files (the
// plugin API and the plugin lifecycle owner) so ejected projects, whose
// sources were copied once at eject time, stay in step with the generated
// registrant. Managed builds already have identical copies from the
// scaffold.
func EnsureRunnerSupport(buildDir, platform string) ([]string, error) {
	switch platform {
	case "android":
		return ensureAndroidRunnerSupport(buildDir)
	case "ios", "xtool":
		return ensureIOSRunnerSupport(buildDir, platform)
	default:
		return nil, fmt.Errorf("EnsureRunnerSupport: unknown platform %q", platform)
	}
}

// IOSRunnerSupportFiles are the hand-written Swift files, relative to the
// ios template dir and to the app's source dir, that drive plugins from the
// app target. (The plugin API itself lives in the Drift/Plugins package,
// which Apply regenerates.)
var IOSRunnerSupportFiles = []string{
	"DriftPlugins.swift",
}

func ensureIOSRunnerSupport(buildDir, platform string) ([]string, error) {
	dir := iosRunnerSourcesDir(buildDir, platform)
	var changed []string
	for _, name := range IOSRunnerSupportFiles {
		content, err := templates.ReadFile("ios/" + name)
		if err != nil {
			return changed, fmt.Errorf("read ios/%s: %w", name, err)
		}
		paths, err := writeIfDifferentSingle(filepath.Join(dir, name), content)
		if err != nil {
			return changed, err
		}
		changed = append(changed, paths...)
	}
	return changed, nil
}

// iosRunnerSourcesDir is where the app target's Swift sources live:
// Runner/ for xcodeproj builds (managed and ejected), Sources/Runner/ for
// xtool.
func iosRunnerSourcesDir(buildDir, platform string) string {
	if platform == "xtool" {
		return filepath.Join(buildDir, "Sources", "Runner")
	}
	return filepath.Join(buildDir, "Runner")
}

func ensureAndroidRunnerSupport(buildDir string) ([]string, error) {
	root := filepath.Join(buildDir, "app", "src", "main", "java", "com", "drift", "runner")
	var changed []string
	for _, f := range AndroidRunnerSupportFiles {
		content, err := templates.ReadFile(f.TemplatePath)
		if err != nil {
			return changed, fmt.Errorf("read %s: %w", f.TemplatePath, err)
		}
		dest := filepath.Join(root, f.Name)
		paths, err := writeIfDifferentSingle(dest, content)
		if err != nil {
			return changed, err
		}
		changed = append(changed, paths...)
	}
	return changed, nil
}

func writeIfDifferentSingle(path string, content []byte) ([]string, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return nil, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return nil, fmt.Errorf("mkdir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", path, err)
	}
	return []string{path}, nil
}
