package plugin

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/go-drift/drift/cmd/drift/internal/templates"
	"github.com/go-drift/drift/pkg/plugin/protocol"
)

// AndroidRunnerSupportFiles names the templates that EnsureRunnerSupport
// writes into an ejected Android project's `com.drift.runner` package.
// They are the exact same bytes scaffold.WriteAndroid copies during a fresh
// scaffold; keeping a single source of truth here prevents semantic drift
// between scaffold output and EnsureRunnerSupport output. (Earlier the two
// surfaces carried duplicated Kotlin source and the MethodHandler signature
// drifted, breaking every Android build that re-applied EnsureRunnerSupport
// after scaffold.)
var AndroidRunnerSupportFiles = []struct {
	Name         string
	TemplatePath string
}{
	{"DriftPluginHost.kt", "android/runner/DriftPluginHost.kt"},
	{"DriftOverlayHost.kt", "android/runner/DriftOverlayHost.kt"},
	{"MethodHandler.kt", "android/runner/MethodHandler.kt"},
}

// WriteRegistrant generates DriftPluginRegistrant for the target platform and
// writes it into buildDir at the fixed runtime-runner path. The body is
// populated from the OpRegistrant* ops in `ops` in source order; an empty
// body is emitted when no such ops are present, so the call site in
// PlatformChannel always resolves.
func WriteRegistrant(buildDir, platform string, ops []protocol.Op) ([]string, error) {
	switch platform {
	case "android":
		return writeAndroidRegistrant(buildDir, ops)
	case "ios", "xtool":
		return writeIOSRegistrant(filepath.Join(iosRunnerSourcesDir(buildDir, platform), "DriftPluginRegistrant.swift"), ops)
	default:
		return nil, fmt.Errorf("WriteRegistrant: unknown platform %q", platform)
	}
}

func writeAndroidRegistrant(buildDir string, ops []protocol.Op) ([]string, error) {
	dest := filepath.Join(buildDir, "app", "src", "main", "java", "com", "drift", "runner", "DriftPluginRegistrant.kt")
	registerBody := androidRegistrantBody(ops)
	preActivityBody := androidPreActivityBody(ops)
	content := []byte("package com.drift.runner\n\n" +
		"import android.app.Activity\n\n" +
		"// Code generated by Drift plugin pipeline. DO NOT EDIT.\n\n" +
		"object DriftPluginRegistrant {\n" +
		"    fun registerAll(host: DriftPluginHost) {\n" +
		registerBody +
		"    }\n\n" +
		"    fun preActivityCreate(activity: Activity) {\n" +
		preActivityBody +
		"    }\n" +
		"}\n")
	return writeIfDifferentSingle(dest, content)
}

func androidRegistrantBody(ops []protocol.Op) string {
	var calls []string
	for _, op := range ops {
		if reg, ok := op.(*protocol.OpRegistrantAndroid); ok && reg.Symbol != "" {
			calls = append(calls, fmt.Sprintf("        %s(host)", reg.Symbol))
		}
	}
	if len(calls) == 0 {
		return ""
	}
	sort.Strings(calls)
	return strings.Join(calls, "\n") + "\n"
}

func androidPreActivityBody(ops []protocol.Op) string {
	var calls []string
	for _, op := range ops {
		if reg, ok := op.(*protocol.OpAndroidPreActivityRegistrant); ok && reg.Symbol != "" {
			calls = append(calls, fmt.Sprintf("        %s(activity)", reg.Symbol))
		}
	}
	if len(calls) == 0 {
		return ""
	}
	sort.Strings(calls)
	return strings.Join(calls, "\n") + "\n"
}

func writeIOSRegistrant(dest string, ops []protocol.Op) ([]string, error) {
	body := iosRegistrantBody(ops)
	methods := iosAppDelegateMethods(ops)
	content := []byte("// Code generated by Drift plugin pipeline. DO NOT EDIT.\n\n" +
		"import UIKit\n\n" +
		"enum DriftPluginRegistrant {\n" +
		"    static func registerAll(host: DriftPluginHost) {\n" +
		body +
		"    }\n" +
		methods +
		"}\n")
	return writeIfDifferentSingle(dest, content)
}

func iosRegistrantBody(ops []protocol.Op) string {
	var calls []string
	for _, op := range ops {
		if reg, ok := op.(*protocol.OpRegistrantIOS); ok && reg.Symbol != "" {
			calls = append(calls, fmt.Sprintf("        %s(host: host)", reg.Symbol))
		}
	}
	if len(calls) == 0 {
		return ""
	}
	sort.Strings(calls)
	return strings.Join(calls, "\n") + "\n"
}

// iosAppDelegateMethods emits the per-callback static methods on
// DriftPluginRegistrant. Every callback in IOSAppDelegateCallbacks gets a
// method, even when no plugins register, so the AppDelegate and
// SceneDelegate templates can call them unconditionally. Drift's own
// dispatch (NotificationHandler.*, DeepLinkHandler.handle) lives inside
// these methods too, so each event has a single dispatch path.
func iosAppDelegateMethods(ops []protocol.Op) string {
	byCallback := groupAppDelegateOpsByCallback(ops)
	var b strings.Builder
	for _, cb := range protocol.IOSAppDelegateCallbacks {
		b.WriteString("\n")
		b.WriteString(emitAppDelegateMethod(cb, byCallback[cb]))
	}
	return b.String()
}

func groupAppDelegateOpsByCallback(ops []protocol.Op) map[protocol.IOSAppDelegateCallback][]string {
	out := make(map[protocol.IOSAppDelegateCallback][]string)
	for _, op := range ops {
		reg, ok := op.(*protocol.OpIOSAppDelegateRegistrant)
		if !ok || reg.Symbol == "" {
			continue
		}
		out[reg.Callback] = append(out[reg.Callback], reg.Symbol)
	}
	for k, syms := range out {
		sort.Strings(syms)
		out[k] = syms
	}
	return out
}

func emitAppDelegateMethod(cb protocol.IOSAppDelegateCallback, symbols []string) string {
	switch cb {
	case protocol.IOSCallbackDidFinishLaunching:
		return emitDidFinishLaunching(symbols)
	case protocol.IOSCallbackOpenURL:
		return emitOpenURL(symbols)
	case protocol.IOSCallbackContinueUserActivity:
		return emitContinueUserActivity(symbols)
	case protocol.IOSCallbackDidRegisterForRemoteNotifications:
		return emitDidRegisterForRemoteNotifications(symbols)
	case protocol.IOSCallbackDidFailToRegisterForRemoteNotifs:
		return emitDidFailToRegisterForRemoteNotifications(symbols)
	case protocol.IOSCallbackDidReceiveRemoteNotification:
		return emitDidReceiveRemoteNotification(symbols)
	}
	return ""
}

func emitDidFinishLaunching(symbols []string) string {
	var b strings.Builder
	b.WriteString("    static func didFinishLaunching(\n")
	b.WriteString("        application: UIApplication,\n")
	b.WriteString("        launchOptions: [UIApplication.LaunchOptionsKey: Any]?\n")
	b.WriteString("    ) {\n")
	b.WriteString("        NotificationHandler.start()\n")
	for _, sym := range symbols {
		fmt.Fprintf(&b, "        %s(application: application, launchOptions: launchOptions)\n", sym)
	}
	b.WriteString("    }\n")
	return b.String()
}

// emitOpenURL emits the URL dispatcher the scene call sites (SceneDelegate
// on xcodeproj builds, SwiftUI .onOpenURL on xtool) invoke. Plugins run in
// lex-sorted symbol order; the first to return true claims the URL and ends
// dispatch, so e.g. an OAuth callback claimed by a sign-in SDK never reaches
// Drift's deep-link channel. Unclaimed URLs go to DeepLinkHandler.
func emitOpenURL(symbols []string) string {
	var b strings.Builder
	b.WriteString("    static func openURL(_ url: URL, source: String) {\n")
	for _, sym := range symbols {
		fmt.Fprintf(&b, "        if %s(url: url) { return }\n", sym)
	}
	b.WriteString("        DeepLinkHandler.handle(url: url, source: source)\n")
	b.WriteString("    }\n")
	return b.String()
}

// emitContinueUserActivity mirrors emitOpenURL for NSUserActivity (universal
// links, Handoff). Unclaimed activities with a webpageURL go to
// DeepLinkHandler.
func emitContinueUserActivity(symbols []string) string {
	var b strings.Builder
	b.WriteString("    static func continueUserActivity(_ userActivity: NSUserActivity, source: String) {\n")
	for _, sym := range symbols {
		fmt.Fprintf(&b, "        if %s(userActivity: userActivity) { return }\n", sym)
	}
	b.WriteString("        if let url = userActivity.webpageURL {\n")
	b.WriteString("            DeepLinkHandler.handle(url: url, source: source)\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	return b.String()
}

func emitDidRegisterForRemoteNotifications(symbols []string) string {
	var b strings.Builder
	b.WriteString("    static func didRegisterForRemoteNotifications(\n")
	b.WriteString("        application: UIApplication,\n")
	b.WriteString("        deviceToken: Data\n")
	b.WriteString("    ) {\n")
	b.WriteString("        NotificationHandler.handleDeviceToken(deviceToken)\n")
	for _, sym := range symbols {
		fmt.Fprintf(&b, "        %s(application: application, deviceToken: deviceToken)\n", sym)
	}
	b.WriteString("    }\n")
	return b.String()
}

func emitDidFailToRegisterForRemoteNotifications(symbols []string) string {
	var b strings.Builder
	b.WriteString("    static func didFailToRegisterForRemoteNotifications(\n")
	b.WriteString("        application: UIApplication,\n")
	b.WriteString("        error: Error\n")
	b.WriteString("    ) {\n")
	b.WriteString("        NotificationHandler.handleRemoteNotificationError(error)\n")
	for _, sym := range symbols {
		fmt.Fprintf(&b, "        %s(application: application, error: error)\n", sym)
	}
	b.WriteString("    }\n")
	return b.String()
}

// emitDidReceiveRemoteNotification runs Drift's own notification dispatch,
// then hands the plugin handlers to
// DriftPluginCoordinator.dispatchBackgroundFetch, which owns the lock +
// timer + once-only scaffold and merges the plugins' results. With no plugin
// handlers the coordinator reports .newData, Drift's historical result.
//
// Keeping the scaffold in the hand-written coordinator means the
// race-condition logic lives in one file the swift-test harness exercises
// directly, and the codegen stays one closure per registered symbol.
func emitDidReceiveRemoteNotification(symbols []string) string {
	var b strings.Builder
	b.WriteString("    static func didReceiveRemoteNotification(\n")
	b.WriteString("        application: UIApplication,\n")
	b.WriteString("        userInfo: [AnyHashable: Any],\n")
	b.WriteString("        completionHandler: @escaping (UIBackgroundFetchResult) -> Void\n")
	b.WriteString("    ) {\n")
	b.WriteString("        NotificationHandler.handleRemoteNotification(userInfo, isForeground: application.applicationState == .active)\n")
	if len(symbols) == 0 {
		b.WriteString("        let handlers: [DriftPluginCoordinator.BackgroundFetchHandler] = []\n")
	} else {
		b.WriteString("        let handlers: [DriftPluginCoordinator.BackgroundFetchHandler] = [\n")
		for _, sym := range symbols {
			fmt.Fprintf(&b, "            { userInfo, completion in %s(userInfo: userInfo, completion: completion) },\n", sym)
		}
		b.WriteString("        ]\n")
	}
	b.WriteString("        DriftPluginCoordinator.dispatchBackgroundFetch(\n")
	b.WriteString("            userInfo: userInfo,\n")
	b.WriteString("            handlers: handlers,\n")
	b.WriteString("            completionHandler: completionHandler\n")
	b.WriteString("        )\n")
	b.WriteString("    }\n")
	return b.String()
}

// EnsureRunnerSupport writes the namespace-isolated com.drift.runner.* support
// files that the runtime needs. On Android, this writes DriftPluginHost.kt
// and MethodHandler.kt so ejected projects (where scaffold.WriteAndroid skips
// these) still have them. On iOS and xtool, this is a no-op: the support
// files live under Runner/ and ride the synchronized-group template.
func EnsureRunnerSupport(buildDir, platform string) ([]string, error) {
	switch platform {
	case "android":
		return ensureAndroidRunnerSupport(buildDir)
	case "ios", "xtool":
		return ensureIOSRunnerSupport(buildDir, platform)
	default:
		return nil, fmt.Errorf("EnsureRunnerSupport: unknown platform %q", platform)
	}
}

// IOSRunnerSupportFiles are the hand-written Swift files the generated
// DriftPluginRegistrant.swift depends on. The managed scaffold already
// copies them with the rest of the iOS templates; EnsureRunnerSupport also
// writes them so ejected projects, whose sources were copied at eject time,
// keep compiling when the generated registrant starts referencing them.
var IOSRunnerSupportFiles = []string{"DriftPluginCoordinator.swift"}

func ensureIOSRunnerSupport(buildDir, platform string) ([]string, error) {
	dir := iosRunnerSourcesDir(buildDir, platform)
	var changed []string
	for _, name := range IOSRunnerSupportFiles {
		content, err := templates.ReadFile("ios/" + name)
		if err != nil {
			return changed, fmt.Errorf("read ios/%s: %w", name, err)
		}
		paths, err := writeIfDifferentSingle(filepath.Join(dir, name), content)
		if err != nil {
			return changed, err
		}
		changed = append(changed, paths...)
	}
	return changed, nil
}

// iosRunnerSourcesDir is where the app target's Swift sources live:
// Runner/ for xcodeproj builds (managed and ejected), Sources/Runner/ for
// xtool.
func iosRunnerSourcesDir(buildDir, platform string) string {
	if platform == "xtool" {
		return filepath.Join(buildDir, "Sources", "Runner")
	}
	return filepath.Join(buildDir, "Runner")
}

func ensureAndroidRunnerSupport(buildDir string) ([]string, error) {
	root := filepath.Join(buildDir, "app", "src", "main", "java", "com", "drift", "runner")
	var changed []string
	for _, f := range AndroidRunnerSupportFiles {
		content, err := templates.ReadFile(f.TemplatePath)
		if err != nil {
			return changed, fmt.Errorf("read %s: %w", f.TemplatePath, err)
		}
		dest := filepath.Join(root, f.Name)
		paths, err := writeIfDifferentSingle(dest, content)
		if err != nil {
			return changed, err
		}
		changed = append(changed, paths...)
	}
	return changed, nil
}

func writeIfDifferentSingle(path string, content []byte) ([]string, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return nil, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return nil, fmt.Errorf("mkdir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", path, err)
	}
	return []string{path}, nil
}
