package plugin

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/go-drift/drift/cmd/drift/internal/templates"
	driftplugin "github.com/go-drift/drift/pkg/plugin"
)

// AndroidRunnerSupportFiles names the templates that EnsureRunnerSupport
// writes into an ejected Android project's `com.drift.runner` package.
// They are the exact same bytes scaffold.WriteAndroid copies during a fresh
// scaffold; keeping a single source of truth here prevents semantic drift
// between scaffold output and EnsureRunnerSupport output. (Earlier the two
// surfaces carried duplicated Kotlin source and the MethodHandler signature
// drifted, breaking every Android build that re-applied EnsureRunnerSupport
// after scaffold.)
var AndroidRunnerSupportFiles = []struct {
	Name         string
	TemplatePath string
}{
	{"DriftPluginHost.kt", "android/runner/DriftPluginHost.kt"},
	{"MethodHandler.kt", "android/runner/MethodHandler.kt"},
}

// WriteRegistrant generates DriftPluginRegistrant for the target platform and
// writes it into buildDir at the fixed runtime-runner path. The body is
// populated from the OpRegistrant* ops in `ops` in source order; an empty
// body is emitted when no such ops are present, so the call site in
// PlatformChannel always resolves.
func WriteRegistrant(buildDir, platform string, ops []driftplugin.Op) ([]string, error) {
	switch platform {
	case "android":
		return writeAndroidRegistrant(buildDir, ops)
	case "ios":
		return writeIOSRegistrant(filepath.Join(buildDir, "Runner", "DriftPluginRegistrant.swift"), ops)
	case "xtool":
		return writeIOSRegistrant(filepath.Join(buildDir, "Sources", "Runner", "DriftPluginRegistrant.swift"), ops)
	default:
		return nil, fmt.Errorf("WriteRegistrant: unknown platform %q", platform)
	}
}

func writeAndroidRegistrant(buildDir string, ops []driftplugin.Op) ([]string, error) {
	dest := filepath.Join(buildDir, "app", "src", "main", "java", "com", "drift", "runner", "DriftPluginRegistrant.kt")
	body := androidRegistrantBody(ops)
	content := []byte("package com.drift.runner\n\n" +
		"// Code generated by Drift plugin pipeline. DO NOT EDIT.\n\n" +
		"object DriftPluginRegistrant {\n" +
		"    fun registerAll(host: DriftPluginHost) {\n" +
		body +
		"    }\n" +
		"}\n")
	return writeIfDifferentSingle(dest, content)
}

func androidRegistrantBody(ops []driftplugin.Op) string {
	var calls []string
	for _, op := range ops {
		if reg, ok := op.(*driftplugin.OpRegistrantAndroid); ok && reg.Symbol != "" {
			calls = append(calls, fmt.Sprintf("        %s(host)", reg.Symbol))
		}
	}
	if len(calls) == 0 {
		return ""
	}
	sort.Strings(calls)
	return strings.Join(calls, "\n") + "\n"
}

func writeIOSRegistrant(dest string, ops []driftplugin.Op) ([]string, error) {
	body := iosRegistrantBody(ops)
	content := []byte("// Code generated by Drift plugin pipeline. DO NOT EDIT.\n\n" +
		"enum DriftPluginRegistrant {\n" +
		"    static func registerAll(host: DriftPluginHost) {\n" +
		body +
		"    }\n" +
		"}\n")
	return writeIfDifferentSingle(dest, content)
}

func iosRegistrantBody(ops []driftplugin.Op) string {
	var calls []string
	for _, op := range ops {
		if reg, ok := op.(*driftplugin.OpRegistrantIOS); ok && reg.Symbol != "" {
			calls = append(calls, fmt.Sprintf("        %s(host: host)", reg.Symbol))
		}
	}
	if len(calls) == 0 {
		return ""
	}
	sort.Strings(calls)
	return strings.Join(calls, "\n") + "\n"
}

// EnsureRunnerSupport writes the namespace-isolated com.drift.runner.* support
// files that the runtime needs. On Android, this writes DriftPluginHost.kt
// and MethodHandler.kt so ejected projects (where scaffold.WriteAndroid skips
// these) still have them. On iOS and xtool, this is a no-op: the support
// files live under Runner/ and ride the synchronized-group template.
func EnsureRunnerSupport(buildDir, platform string) ([]string, error) {
	switch platform {
	case "android":
		return ensureAndroidRunnerSupport(buildDir)
	case "ios", "xtool":
		return nil, nil
	default:
		return nil, fmt.Errorf("EnsureRunnerSupport: unknown platform %q", platform)
	}
}

func ensureAndroidRunnerSupport(buildDir string) ([]string, error) {
	root := filepath.Join(buildDir, "app", "src", "main", "java", "com", "drift", "runner")
	var changed []string
	for _, f := range AndroidRunnerSupportFiles {
		content, err := templates.ReadFile(f.TemplatePath)
		if err != nil {
			return changed, fmt.Errorf("read %s: %w", f.TemplatePath, err)
		}
		dest := filepath.Join(root, f.Name)
		paths, err := writeIfDifferentSingle(dest, content)
		if err != nil {
			return changed, err
		}
		changed = append(changed, paths...)
	}
	return changed, nil
}

func writeIfDifferentSingle(path string, content []byte) ([]string, error) {
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, content) {
		return nil, nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return nil, fmt.Errorf("mkdir for %s: %w", path, err)
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return nil, fmt.Errorf("write %s: %w", path, err)
	}
	return []string{path}, nil
}
