package mutate

import (
	"errors"
	"fmt"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/go-drift/drift/pkg/plugin/protocol"
)

// pluginPackageHeader is the byte-stable preamble of the generated
// Drift/Plugins/Package.swift. The build pipeline relies on the file being
// regenerated only when the op set changes; do not interpolate timestamps,
// op counts, or other unstable values here.
const pluginPackageHeader = `// swift-tools-version:5.9
// Generated by Drift plugin sync. Do not edit by hand.
import PackageDescription
`

// pluginAPIModule is the module holding the plugin API (DriftPlugin,
// DriftPluginHost, ...) that plugin modules and the app both import.
const pluginAPIModule = "DriftPluginAPI"

// emptyPluginSource stands in for the sources of a plugin that only adds
// SwiftPM dependencies: SwiftPM rejects a target with no sources.
const emptyPluginSource = `// Generated by Drift plugin sync. Do not edit by hand.
//
// This plugin ships no Swift sources; its module exists to link the
// SwiftPM products it depends on.
`

// PluginModule returns the Swift module that holds a plugin's sources,
// named after the plugin (its Plugin.Name()).
func PluginModule(pluginName string) string { return "DriftPlugin_" + pluginName }

// PluginPackage is the content of the generated Drift/Plugins package.
type PluginPackage struct {
	// API holds the DriftPluginAPI module's sources, by file name.
	API map[string][]byte
	// Deps are the SwiftPM dependencies plugins request.
	Deps []*protocol.OpIOSAddPackageDependency
	// Sources are the plugins' Swift sources.
	Sources []*protocol.OpAddIOSSource
}

// WritePluginPackage regenerates the Drift/Plugins package at root: the
// DriftPluginAPI target, one DriftPlugin_<name> target per plugin with
// sources or SwiftPM dependencies (depending on DriftPluginAPI and its own
// products), and a DriftPlugins library product listing them all, which
// both iOS build paths link. Each plugin is its own Swift module, so
// plugins cannot clash on type or file names, and a plugin imports the
// SwiftPM products it depends on directly.
//
// The directory is Drift-owned: anything under Sources/ that this build
// did not write is removed, so a dropped plugin's module goes with it.
// Byte-identical output produces no writes. Returns written and removed
// paths.
func WritePluginPackage(root string, pkg PluginPackage) ([]string, error) {
	files := map[string][]byte{}
	for name, content := range pkg.API {
		files[filepath.Join("Sources", pluginAPIModule, name)] = content
	}
	plugins := map[string]bool{}
	for _, op := range pkg.Sources {
		content, err := protocol.DecodeContent(op.Content)
		if err != nil {
			return nil, fmt.Errorf("decode iOS source %s: %w", op.RelPath, err)
		}
		files[filepath.Join("Sources", PluginModule(op.PluginID()), op.Group, filepath.FromSlash(op.RelPath))] = content
		plugins[op.PluginID()] = true
	}
	for _, op := range pkg.Deps {
		if !plugins[op.PluginID()] {
			files[filepath.Join("Sources", PluginModule(op.PluginID()), "DriftPluginEmpty.swift")] = []byte(emptyPluginSource)
		}
	}
	files["Package.swift"] = []byte(renderPluginPackage(pkg.Deps, slices.Collect(maps.Keys(plugins))))

	var changed []string
	for _, rel := range slices.Sorted(maps.Keys(files)) {
		p := filepath.Join(root, rel)
		ch, err := writeIfDifferent(p, files[rel])
		if err != nil {
			return changed, fmt.Errorf("write %s: %w", p, err)
		}
		if ch {
			changed = append(changed, p)
		}
	}
	removed, err := pruneTree(filepath.Join(root, "Sources"), func(path string) bool {
		rel, err := filepath.Rel(root, path)
		return err == nil && files[rel] != nil
	})
	changed = append(changed, removed...)
	if err != nil {
		return changed, err
	}
	// The single wrapper source of the earlier one-target layout.
	if err := os.Remove(filepath.Join(root, "Empty.swift")); err == nil {
		changed = append(changed, filepath.Join(root, "Empty.swift"))
	}
	return changed, nil
}

// pruneTree removes every file under dir that keep rejects, then the
// directories left empty. Returns the removed files.
func pruneTree(dir string, keep func(path string) bool) ([]string, error) {
	var removed, dirs []string
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if errors.Is(err, fs.ErrNotExist) {
			return nil
		}
		if err != nil {
			return err
		}
		if d.IsDir() {
			dirs = append(dirs, path)
			return nil
		}
		if keep(path) {
			return nil
		}
		if err := os.Remove(path); err != nil {
			return err
		}
		removed = append(removed, path)
		return nil
	})
	// Deepest first, so a parent empties after its children.
	for i := len(dirs) - 1; i >= 0; i-- {
		_ = os.Remove(dirs[i]) // fails, harmlessly, while not empty
	}
	return removed, err
}

// renderPluginPackage returns the Drift/Plugins/Package.swift content.
// Several plugins may depend on one package (same URL and requirement,
// which conflict validation guarantees); it is declared once, and each
// plugin's target lists the products it asked for. Op validation
// guarantees every string is safe to quote verbatim as a Swift literal.
func renderPluginPackage(deps []*protocol.OpIOSAddPackageDependency, sourcePlugins []string) string {
	type dep struct {
		url string
		req protocol.SPMRequirement
	}
	packages := map[string]dep{}
	products := map[string]map[string]string{} // plugin -> product -> package identity
	plugins := map[string]bool{}
	for _, p := range sourcePlugins {
		plugins[p] = true
	}
	for _, op := range deps {
		packages[op.URL] = dep{url: op.URL, req: op.Requirement}
		plugin := op.PluginID()
		plugins[plugin] = true
		if products[plugin] == nil {
			products[plugin] = map[string]string{}
		}
		for _, product := range op.Products {
			products[plugin][product] = protocol.SPMPackageIdentity(op.URL)
		}
	}
	names := slices.Sorted(maps.Keys(plugins))
	targets := []string{swiftString(pluginAPIModule)}
	for _, name := range names {
		targets = append(targets, swiftString(PluginModule(name)))
	}

	var b strings.Builder
	b.WriteString(pluginPackageHeader)
	b.WriteString("\nlet package = Package(\n")
	b.WriteString("    name: \"DriftPlugins\",\n")
	b.WriteString("    platforms: [.iOS(.v16)],\n")
	b.WriteString("    products: [\n")
	fmt.Fprintf(&b, "        .library(name: \"DriftPlugins\", targets: [%s])\n", strings.Join(targets, ", "))
	b.WriteString("    ],\n")
	b.WriteString("    dependencies: [\n")
	for _, url := range slices.Sorted(maps.Keys(packages)) {
		fmt.Fprintf(&b, "        .package(url: %s, %s),\n", swiftString(url), formatSPMRequirement(packages[url].req))
	}
	b.WriteString("    ],\n")
	b.WriteString("    targets: [\n")
	fmt.Fprintf(&b, "        .target(name: %s, path: \"Sources/%s\"),\n", swiftString(pluginAPIModule), pluginAPIModule)
	for _, name := range names {
		module := PluginModule(name)
		b.WriteString("        .target(\n")
		fmt.Fprintf(&b, "            name: %s,\n", swiftString(module))
		b.WriteString("            dependencies: [\n")
		fmt.Fprintf(&b, "                %s,\n", swiftString(pluginAPIModule))
		for _, product := range slices.Sorted(maps.Keys(products[name])) {
			fmt.Fprintf(&b, "                .product(name: %s, package: %s),\n", swiftString(product), swiftString(products[name][product]))
		}
		b.WriteString("            ],\n")
		fmt.Fprintf(&b, "            path: \"Sources/%s\"\n", module)
		b.WriteString("        ),\n")
	}
	b.WriteString("    ]\n")
	b.WriteString(")\n")
	return b.String()
}

// formatSPMRequirement returns the clause that follows `url: "..."` inside
// `.package(url:..., ...)`. The requirement is already validated, so every
// kind is known.
func formatSPMRequirement(req protocol.SPMRequirement) string {
	v := swiftString(req.Value)
	switch req.Kind {
	case protocol.SPMFrom:
		return "from: " + v
	case protocol.SPMExact:
		return "exact: " + v
	case protocol.SPMBranch:
		return "branch: " + v
	case protocol.SPMRevision:
		return "revision: " + v
	case protocol.SPMUpToNextMajor:
		return ".upToNextMajor(from: " + v + ")"
	case protocol.SPMUpToNextMinor:
		return ".upToNextMinor(from: " + v + ")"
	case protocol.SPMRange:
		return v + "..<" + swiftString(req.Upper)
	}
	panic(fmt.Sprintf("formatSPMRequirement: unvalidated kind %q", req.Kind))
}

// swiftString quotes s as a Swift string literal. Callers only pass values
// that op validation has checked contain no quote,
// backslash, or newline, so no escaping is needed. (Go's %q is not a
// substitute: its escapes, e.g. \x00, are not valid Swift.)
func swiftString(s string) string { return `"` + s + `"` }
