package mutate

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/go-drift/drift/pkg/plugin/protocol"
)

// emptySwiftSource is the trivial source the wrapper target ships. SPM
// rejects targets with zero sources; this file's job is to exist. The
// header marks it as generated so anyone browsing the project sees why.
const emptySwiftSource = `// Generated by Drift plugin sync. Do not edit by hand.
//
// The wrapper target this file belongs to re-exposes plugin SPM products
// to the Drift app target without requiring the app's xcodeproj to know
// about each plugin individually. SPM rejects targets with no sources,
// so this file's job is purely structural.
`

// pluginPackageHeader is the byte-stable preamble of the generated
// Drift/Plugins/Package.swift. The build pipeline relies on the file being
// regenerated only when the op set changes; do not interpolate timestamps,
// op counts, or other unstable values here.
const pluginPackageHeader = `// swift-tools-version:5.9
// Generated by Drift plugin sync. Do not edit by hand.
import PackageDescription
`

// ApplyPluginPackage regenerates the sidecar Drift/Plugins/Package.swift
// (and its Empty.swift source) from the given ops. Both iOS build paths
// (xcodeproj and xtool) reference this sidecar via a local-package
// declaration; plugin builds only ever touch this directory, never the
// project files themselves.
//
// Zero ops produces a valid empty wrapper target, so the scaffolded
// `.package(path: "Drift/Plugins")` reference always resolves.
//
// Idempotent: byte-identical input produces no writes. Ops are sorted by
// URL internally for deterministic output.
func ApplyPluginPackage(packageRoot string, ops []*protocol.OpIOSAddPackageDependency) ([]string, error) {
	pkgContent, err := renderPluginPackage(ops)
	if err != nil {
		return nil, err
	}
	var changed []string
	for _, f := range []struct{ name, content string }{
		{"Package.swift", pkgContent},
		{"Empty.swift", emptySwiftSource},
	} {
		p := filepath.Join(packageRoot, f.name)
		ch, err := writeIfDifferent(p, []byte(f.content))
		if err != nil {
			return changed, fmt.Errorf("write %s: %w", p, err)
		}
		if ch {
			changed = append(changed, p)
		}
	}
	return changed, nil
}

// renderPluginPackage returns the Drift/Plugins/Package.swift bytes for the
// given ops. Op validation guarantees every string is safe to quote
// verbatim as a Swift literal.
func renderPluginPackage(ops []*protocol.OpIOSAddPackageDependency) (string, error) {
	sorted := append([]*protocol.OpIOSAddPackageDependency(nil), ops...)
	sort.SliceStable(sorted, func(i, j int) bool { return sorted[i].URL < sorted[j].URL })

	var b strings.Builder
	b.WriteString(pluginPackageHeader)
	b.WriteString("\nlet package = Package(\n")
	b.WriteString("    name: \"DriftPlugins\",\n")
	b.WriteString("    platforms: [.iOS(.v16)],\n")
	b.WriteString("    products: [\n")
	b.WriteString("        .library(name: \"DriftPlugins\", targets: [\"DriftPlugins\"])\n")
	b.WriteString("    ],\n")
	b.WriteString("    dependencies: [\n")
	for _, op := range sorted {
		fmt.Fprintf(&b, "        .package(url: %s, %s),\n", swiftString(op.URL), formatSPMRequirement(op.Requirement))
	}
	b.WriteString("    ],\n")
	b.WriteString("    targets: [\n")
	b.WriteString("        .target(\n")
	b.WriteString("            name: \"DriftPlugins\",\n")
	b.WriteString("            dependencies: [\n")
	for _, op := range sorted {
		identity := protocol.SPMPackageIdentity(op.URL)
		products := append([]string(nil), op.Products...)
		sort.Strings(products)
		for _, product := range products {
			fmt.Fprintf(&b, "                .product(name: %s, package: %s),\n", swiftString(product), swiftString(identity))
		}
	}
	b.WriteString("            ],\n")
	b.WriteString("            path: \".\",\n")
	b.WriteString("            sources: [\"Empty.swift\"]\n")
	b.WriteString("        )\n")
	b.WriteString("    ]\n")
	b.WriteString(")\n")
	return b.String(), nil
}

// formatSPMRequirement returns the clause that follows `url: "..."` inside
// `.package(url:..., ...)`. The requirement is already validated, so every
// kind is known.
func formatSPMRequirement(req protocol.SPMRequirement) string {
	v := swiftString(req.Value)
	switch req.Kind {
	case protocol.SPMFrom:
		return "from: " + v
	case protocol.SPMExact:
		return "exact: " + v
	case protocol.SPMBranch:
		return "branch: " + v
	case protocol.SPMRevision:
		return "revision: " + v
	case protocol.SPMUpToNextMajor:
		return ".upToNextMajor(from: " + v + ")"
	case protocol.SPMUpToNextMinor:
		return ".upToNextMinor(from: " + v + ")"
	case protocol.SPMRange:
		return v + "..<" + swiftString(req.Upper)
	}
	panic(fmt.Sprintf("formatSPMRequirement: unvalidated kind %q", req.Kind))
}

// swiftString quotes s as a Swift string literal. Callers only pass values
// that op validation has checked contain no quote,
// backslash, or newline, so no escaping is needed. (Go's %q is not a
// substitute: its escapes, e.g. \x00, are not valid Swift.)
func swiftString(s string) string { return `"` + s + `"` }
