package mutate

import (
	"encoding/base64"
	"os"
	"path/filepath"
	"testing"

	driftplugin "github.com/go-drift/drift/pkg/plugin"
	"github.com/go-drift/drift/pkg/plugin/protocol"
)

var testAPI = map[string][]byte{"DriftPlugin.swift": []byte("public protocol DriftPlugin {}\n")}

func swiftSource(plugin, group, rel, body string) *protocol.OpAddIOSSource {
	return &protocol.OpAddIOSSource{
		Base:    protocol.Base{Pkg: "github.com/acme/" + plugin, Ident: plugin},
		Group:   group,
		RelPath: rel,
		Content: base64.StdEncoding.EncodeToString([]byte(body)),
	}
}

func spmDep(plugin, url string, req protocol.SPMRequirement, products ...string) *protocol.OpIOSAddPackageDependency {
	return &protocol.OpIOSAddPackageDependency{
		Base:        protocol.Base{Pkg: "github.com/acme/" + plugin, Ident: plugin},
		URL:         url,
		Requirement: req,
		Products:    products,
	}
}

func readFile(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

// With no plugins the package still exists with the API module, which the
// app target imports unconditionally.
func TestWritePluginPackageEmpty(t *testing.T) {
	root := filepath.Join(t.TempDir(), "Drift", "Plugins")
	if _, err := WritePluginPackage(root, PluginPackage{API: testAPI}); err != nil {
		t.Fatal(err)
	}
	want := `// swift-tools-version:5.9
// Generated by Drift plugin sync. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "DriftPlugins",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "DriftPlugins", targets: ["DriftPluginAPI"])
    ],
    dependencies: [
    ],
    targets: [
        .target(name: "DriftPluginAPI", path: "Sources/DriftPluginAPI"),
    ]
)
`
	if got := readFile(t, filepath.Join(root, "Package.swift")); got != want {
		t.Errorf("Package.swift:\n%s\nwant:\n%s", got, want)
	}
	if got := readFile(t, filepath.Join(root, "Sources/DriftPluginAPI/DriftPlugin.swift")); got != string(testAPI["DriftPlugin.swift"]) {
		t.Errorf("API source not written")
	}
}

// Each plugin is a module depending on the API and on the products it
// asked for. Plugins sharing a package declare it once.
func TestWritePluginPackageFirebaseSnapshot(t *testing.T) {
	root := filepath.Join(t.TempDir(), "Drift", "Plugins")
	const sdk = "https://github.com/firebase/firebase-ios-sdk"
	pkg := PluginPackage{
		API: testAPI,
		Deps: []*protocol.OpIOSAddPackageDependency{
			spmDep("firebase", sdk, driftplugin.SPMRequirementFrom("11.0.0"), "FirebaseMessaging", "FirebaseCore"),
			spmDep("analytics", sdk, driftplugin.SPMRequirementFrom("11.0.0"), "FirebaseAnalytics"),
			spmDep("sentry", "https://github.com/getsentry/sentry-cocoa", protocol.SPMRequirement{Kind: "exact", Value: "8.20.0"}, "Sentry"),
		},
		Sources: []*protocol.OpAddIOSSource{
			swiftSource("firebase", "Messaging", "FirebasePlugin.swift", "import FirebaseCore\n"),
			swiftSource("analytics", "Main", "AnalyticsPlugin.swift", "import FirebaseAnalytics\n"),
		},
	}
	if _, err := WritePluginPackage(root, pkg); err != nil {
		t.Fatal(err)
	}
	want := `// swift-tools-version:5.9
// Generated by Drift plugin sync. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "DriftPlugins",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "DriftPlugins", targets: ["DriftPluginAPI", "DriftPlugin_analytics", "DriftPlugin_firebase", "DriftPlugin_sentry"])
    ],
    dependencies: [
        .package(url: "https://github.com/firebase/firebase-ios-sdk", from: "11.0.0"),
        .package(url: "https://github.com/getsentry/sentry-cocoa", exact: "8.20.0"),
    ],
    targets: [
        .target(name: "DriftPluginAPI", path: "Sources/DriftPluginAPI"),
        .target(
            name: "DriftPlugin_analytics",
            dependencies: [
                "DriftPluginAPI",
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk"),
            ],
            path: "Sources/DriftPlugin_analytics"
        ),
        .target(
            name: "DriftPlugin_firebase",
            dependencies: [
                "DriftPluginAPI",
                .product(name: "FirebaseCore", package: "firebase-ios-sdk"),
                .product(name: "FirebaseMessaging", package: "firebase-ios-sdk"),
            ],
            path: "Sources/DriftPlugin_firebase"
        ),
        .target(
            name: "DriftPlugin_sentry",
            dependencies: [
                "DriftPluginAPI",
                .product(name: "Sentry", package: "sentry-cocoa"),
            ],
            path: "Sources/DriftPlugin_sentry"
        ),
    ]
)
`
	if got := readFile(t, filepath.Join(root, "Package.swift")); got != want {
		t.Errorf("Package.swift:\n%s\nwant:\n%s", got, want)
	}
	if got := readFile(t, filepath.Join(root, "Sources/DriftPlugin_firebase/Messaging/FirebasePlugin.swift")); got != "import FirebaseCore\n" {
		t.Errorf("plugin source = %q", got)
	}
	// sentry ships no sources, so its module gets a placeholder.
	if _, err := os.Stat(filepath.Join(root, "Sources/DriftPlugin_sentry/DriftPluginEmpty.swift")); err != nil {
		t.Errorf("placeholder missing: %v", err)
	}
}

func TestWritePluginPackageIdempotentAndPrunes(t *testing.T) {
	root := filepath.Join(t.TempDir(), "Drift", "Plugins")
	full := PluginPackage{API: testAPI, Sources: []*protocol.OpAddIOSSource{
		swiftSource("splash", "Splash", "Splash.swift", "// splash\n"),
		swiftSource("camera", "Camera", "Camera.swift", "// camera\n"),
	}}
	if _, err := WritePluginPackage(root, full); err != nil {
		t.Fatal(err)
	}
	if changed, err := WritePluginPackage(root, full); err != nil || len(changed) != 0 {
		t.Fatalf("rerun should write nothing: %v %v", changed, err)
	}
	// An earlier layout's wrapper source is removed.
	if err := os.WriteFile(filepath.Join(root, "Empty.swift"), nil, 0o644); err != nil {
		t.Fatal(err)
	}

	// Dropping the camera plugin removes its module.
	full.Sources = full.Sources[:1]
	if _, err := WritePluginPackage(root, full); err != nil {
		t.Fatal(err)
	}
	for _, gone := range []string{"Sources/DriftPlugin_camera", "Empty.swift"} {
		if _, err := os.Stat(filepath.Join(root, gone)); !os.IsNotExist(err) {
			t.Errorf("%s should be removed: %v", gone, err)
		}
	}
	if _, err := os.Stat(filepath.Join(root, "Sources/DriftPlugin_splash/Splash/Splash.swift")); err != nil {
		t.Errorf("kept plugin's source missing: %v", err)
	}
}

func TestFormatSPMRequirement(t *testing.T) {
	cases := []struct {
		name string
		req  protocol.SPMRequirement
		want string
	}{
		{"from", protocol.SPMRequirement{Kind: "from", Value: "1.0.0"}, `from: "1.0.0"`},
		{"exact", protocol.SPMRequirement{Kind: "exact", Value: "1.0.0"}, `exact: "1.0.0"`},
		{"branch", protocol.SPMRequirement{Kind: "branch", Value: "main"}, `branch: "main"`},
		{"revision", protocol.SPMRequirement{Kind: "revision", Value: "abc123"}, `revision: "abc123"`},
		{"upToNextMajor", protocol.SPMRequirement{Kind: "upToNextMajor", Value: "1.0.0"}, `.upToNextMajor(from: "1.0.0")`},
		{"upToNextMinor", protocol.SPMRequirement{Kind: "upToNextMinor", Value: "1.5.0"}, `.upToNextMinor(from: "1.5.0")`},
		{"range", protocol.SPMRequirement{Kind: "range", Value: "1.0.0", Upper: "2.0.0"}, `"1.0.0"..<"2.0.0"`},
	}
	for _, tc := range cases {
		if got := formatSPMRequirement(tc.req); got != tc.want {
			t.Errorf("%s: got %q, want %q", tc.name, got, tc.want)
		}
	}
}
