package mutate

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	driftplugin "github.com/go-drift/drift/pkg/plugin"
	"github.com/go-drift/drift/pkg/plugin/protocol"
)

func TestApplyPluginPackageEmptyOpsProducesValidWrapper(t *testing.T) {
	dir := t.TempDir()
	root := filepath.Join(dir, "Drift", "Plugins")
	changed, err := ApplyPluginPackage(root, nil)
	if err != nil {
		t.Fatalf("apply empty: %v", err)
	}
	if len(changed) != 2 {
		t.Errorf("expected 2 files (Package.swift + Empty.swift), got %v", changed)
	}
	body, err := os.ReadFile(filepath.Join(root, "Package.swift"))
	if err != nil {
		t.Fatalf("read Package.swift: %v", err)
	}
	s := string(body)
	required := []string{
		"// swift-tools-version:5.9",
		`name: "DriftPlugins"`,
		`platforms: [.iOS(.v16)]`,
		`.library(name: "DriftPlugins", targets: ["DriftPlugins"])`,
		`sources: ["Empty.swift"]`,
	}
	for _, want := range required {
		if !strings.Contains(s, want) {
			t.Errorf("empty wrapper missing %q:\n%s", want, s)
		}
	}
	emptyBody, err := os.ReadFile(filepath.Join(root, "Empty.swift"))
	if err != nil {
		t.Fatalf("read Empty.swift: %v", err)
	}
	if !strings.Contains(string(emptyBody), "Generated by Drift plugin sync") {
		t.Errorf("Empty.swift missing generated header:\n%s", emptyBody)
	}
}

func TestApplyPluginPackagePopulated(t *testing.T) {
	dir := t.TempDir()
	root := filepath.Join(dir, "Drift", "Plugins")
	ops := []*protocol.OpIOSAddPackageDependency{
		{
			Base:        protocol.Base{Pkg: "github.com/foo/firebase"},
			URL:         "https://github.com/firebase/firebase-ios-sdk",
			Requirement: driftplugin.SPMRequirementFrom("10.0.0"),
			Products:    []string{"FirebaseAnalytics", "FirebaseAuth"},
		},
	}
	if _, err := ApplyPluginPackage(root, ops); err != nil {
		t.Fatalf("apply: %v", err)
	}
	body, _ := os.ReadFile(filepath.Join(root, "Package.swift"))
	s := string(body)
	required := []string{
		`.package(url: "https://github.com/firebase/firebase-ios-sdk", from: "10.0.0")`,
		`.product(name: "FirebaseAnalytics", package: "firebase-ios-sdk")`,
		`.product(name: "FirebaseAuth", package: "firebase-ios-sdk")`,
	}
	for _, want := range required {
		if !strings.Contains(s, want) {
			t.Errorf("missing %q:\n%s", want, s)
		}
	}
}

func TestApplyPluginPackageIdempotent(t *testing.T) {
	dir := t.TempDir()
	root := filepath.Join(dir, "Drift", "Plugins")
	ops := []*protocol.OpIOSAddPackageDependency{
		{
			Base:        protocol.Base{Pkg: "p"},
			URL:         "https://github.com/foo/bar",
			Requirement: driftplugin.SPMRequirementFrom("1.0.0"),
			Products:    []string{"Bar"},
		},
	}
	if _, err := ApplyPluginPackage(root, ops); err != nil {
		t.Fatalf("first: %v", err)
	}
	changed, err := ApplyPluginPackage(root, ops)
	if err != nil {
		t.Fatalf("second: %v", err)
	}
	if len(changed) != 0 {
		t.Errorf("expected zero changes on rerun, got %v", changed)
	}
}

// URL order in the input must not affect the output. Mutator sorts
// internally for deterministic output.
func TestApplyPluginPackageDeterministicOrder(t *testing.T) {
	dir := t.TempDir()
	root := filepath.Join(dir, "Drift", "Plugins")
	a := &protocol.OpIOSAddPackageDependency{
		Base:        protocol.Base{Pkg: "p"},
		URL:         "https://github.com/aaa/aaa",
		Requirement: driftplugin.SPMRequirementFrom("1.0.0"),
		Products:    []string{"AAA"},
	}
	b := &protocol.OpIOSAddPackageDependency{
		Base:        protocol.Base{Pkg: "p"},
		URL:         "https://github.com/zzz/zzz",
		Requirement: driftplugin.SPMRequirementFrom("1.0.0"),
		Products:    []string{"ZZZ"},
	}
	if _, err := ApplyPluginPackage(root, []*protocol.OpIOSAddPackageDependency{b, a}); err != nil {
		t.Fatalf("first: %v", err)
	}
	first, _ := os.ReadFile(filepath.Join(root, "Package.swift"))

	if _, err := ApplyPluginPackage(root, []*protocol.OpIOSAddPackageDependency{a, b}); err != nil {
		t.Fatalf("second: %v", err)
	}
	second, _ := os.ReadFile(filepath.Join(root, "Package.swift"))

	if string(first) != string(second) {
		t.Errorf("output not stable under input reordering:\nfirst:\n%s\nsecond:\n%s", first, second)
	}
	// aaa must appear before zzz regardless of input order.
	aaa := strings.Index(string(first), "aaa/aaa")
	zzz := strings.Index(string(first), "zzz/zzz")
	if aaa > zzz {
		t.Errorf("lex order violated; aaa should precede zzz:\n%s", first)
	}
}

func TestApplyPluginPackageRequirementKinds(t *testing.T) {
	cases := []struct {
		name string
		req  protocol.SPMRequirement
		want string
	}{
		{"from", protocol.SPMRequirement{Kind: "from", Value: "1.0.0"}, `from: "1.0.0"`},
		{"exact", protocol.SPMRequirement{Kind: "exact", Value: "1.0.0"}, `exact: "1.0.0"`},
		{"branch", protocol.SPMRequirement{Kind: "branch", Value: "main"}, `branch: "main"`},
		{"revision", protocol.SPMRequirement{Kind: "revision", Value: "abc123"}, `revision: "abc123"`},
		{"upToNextMajor", protocol.SPMRequirement{Kind: "upToNextMajor", Value: "1.0.0"}, `.upToNextMajor(from: "1.0.0")`},
		{"upToNextMinor", protocol.SPMRequirement{Kind: "upToNextMinor", Value: "1.5.0"}, `.upToNextMinor(from: "1.5.0")`},
		{"range", protocol.SPMRequirement{Kind: "range", Value: "1.0.0", Upper: "2.0.0"}, `"1.0.0"..<"2.0.0"`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := formatSPMRequirement(tc.req)
			if got != tc.want {
				t.Errorf("formatSPMRequirement(%+v) = %q, want %q", tc.req, got, tc.want)
			}
		})
	}
}

func TestApplyPluginPackageFirebaseSnapshot(t *testing.T) {
	dir := t.TempDir()
	root := filepath.Join(dir, "Drift", "Plugins")
	ops := []*protocol.OpIOSAddPackageDependency{
		{
			Base:        protocol.Base{Pkg: "github.com/foo/firebase"},
			URL:         "https://github.com/firebase/firebase-ios-sdk",
			Requirement: driftplugin.SPMRequirementFrom("10.0.0"),
			Products:    []string{"FirebaseAnalytics", "FirebaseAuth", "FirebaseFirestore"},
		},
		{
			Base:        protocol.Base{Pkg: "github.com/foo/sentry"},
			URL:         "https://github.com/getsentry/sentry-cocoa",
			Requirement: protocol.SPMRequirement{Kind: "exact", Value: "8.20.0"},
			Products:    []string{"Sentry"},
		},
	}
	if _, err := ApplyPluginPackage(root, ops); err != nil {
		t.Fatalf("apply: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(root, "Package.swift"))
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	want := `// swift-tools-version:5.9
// Generated by Drift plugin sync. Do not edit by hand.
import PackageDescription

let package = Package(
    name: "DriftPlugins",
    platforms: [.iOS(.v16)],
    products: [
        .library(name: "DriftPlugins", targets: ["DriftPlugins"])
    ],
    dependencies: [
        .package(url: "https://github.com/firebase/firebase-ios-sdk", from: "10.0.0"),
        .package(url: "https://github.com/getsentry/sentry-cocoa", exact: "8.20.0"),
    ],
    targets: [
        .target(
            name: "DriftPlugins",
            dependencies: [
                .product(name: "FirebaseAnalytics", package: "firebase-ios-sdk"),
                .product(name: "FirebaseAuth", package: "firebase-ios-sdk"),
                .product(name: "FirebaseFirestore", package: "firebase-ios-sdk"),
                .product(name: "Sentry", package: "sentry-cocoa"),
            ],
            path: ".",
            sources: ["Empty.swift"]
        )
    ]
)
`
	if string(got) != want {
		t.Errorf("snapshot drift; if intentional, update the golden literal in this test.\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}
}

// Plugins sharing a package (same URL and requirement, which Validate
// guarantees) declare it once with the union of their products.
func TestApplyPluginPackageMergesSharedPackage(t *testing.T) {
	root := t.TempDir()
	mk := func(pkg string, products ...string) *protocol.OpIOSAddPackageDependency {
		return &protocol.OpIOSAddPackageDependency{
			Base:        protocol.Base{Pkg: pkg},
			URL:         "https://github.com/firebase/firebase-ios-sdk",
			Requirement: driftplugin.SPMRequirementFrom("11.0.0"),
			Products:    products,
		}
	}
	ops := []*protocol.OpIOSAddPackageDependency{mk("a", "FirebaseMessaging", "FirebaseCore"), mk("b", "FirebaseCore", "FirebaseAnalytics")}
	if _, err := ApplyPluginPackage(root, ops); err != nil {
		t.Fatalf("apply: %v", err)
	}
	got, err := os.ReadFile(filepath.Join(root, "Package.swift"))
	if err != nil {
		t.Fatal(err)
	}
	s := string(got)
	if n := strings.Count(s, ".package(url:"); n != 1 {
		t.Errorf("want one package declaration, got %d:\n%s", n, s)
	}
	for _, p := range []string{"FirebaseAnalytics", "FirebaseCore", "FirebaseMessaging"} {
		if n := strings.Count(s, `.product(name: "`+p+`"`); n != 1 {
			t.Errorf("want product %s once, got %d:\n%s", p, n, s)
		}
	}
}
