//go:build drift_tool

// Code generated by drift CLI from drift.yaml. DO NOT EDIT.
// Regenerated by drift build/run/plugin sync.

package main

import (
	driftplugin "github.com/go-drift/drift/pkg/plugin"

	firebasespike "example.com/firebasespike/plugin"
)

func main() {
	driftplugin.Main(
		driftplugin.Bind("example.com/firebasespike/plugin", firebasespike.Plugin),
	)
}
