import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        description: 'Learn how to build apps with Drift.',
      },
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          items: [
            'guides/getting-started',
            'guides/eject',
            'guides/xtool-setup',
          ],
        },
        {
          type: 'category',
          label: 'Core Concepts',
          items: [
            'guides/widgets',
            'guides/layout',
            'guides/state-management',
            'guides/theming',
          ],
        },
        {
          type: 'category',
          label: 'User Interface',
          items: [
            'guides/navigation',
            'guides/overlay',
            'guides/gestures',
            'guides/forms',
            'guides/animation',
            'guides/lottie',
            'guides/accessibility',
          ],
        },
        {
          type: 'category',
          label: 'Platform Integration',
          items: [
            'guides/platform',
            'guides/media-player',
          ],
        },
        {
          type: 'category',
          label: 'Developer Tools',
          items: [
            'guides/error-handling-and-debugging',
            'guides/testing',
          ],
        },
        {
          type: 'category',
          label: 'Contributing',
          items: [
            'guides/contributing',
            'guides/skia',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Widget Catalog',
      link: {
        type: 'generated-index',
        description: 'Find detailed usage for every Drift widget.',
      },
      items: [
        {
          type: 'category',
          label: 'Layout',
          items: [
            'catalog/layout/column-row',
            'catalog/layout/stack-positioned',
            'catalog/layout/wrap',
            'catalog/layout/container-decoratedbox',
            'catalog/layout/sizedbox',
            'catalog/layout/padding',
            'catalog/layout/expanded-flexible',
            'catalog/layout/center-align',
            'catalog/layout/safearea',
            'catalog/layout/layout-builder',
          ],
        },
        {
          type: 'category',
          label: 'Display',
          items: [
            'catalog/display/text',
            'catalog/display/rich-text',
            'catalog/display/icon',
            'catalog/display/image-svg',
            'catalog/display/lottie',
            'catalog/display/divider',
          ],
        },
        {
          type: 'category',
          label: 'Input',
          items: [
            'catalog/input/button',
            'catalog/input/textfield',
            'catalog/input/checkbox-radio',
            'catalog/input/switch-toggle',
            'catalog/input/dropdown',
            'catalog/input/datepicker-timepicker',
          ],
        },
        {
          type: 'category',
          label: 'Lists & Scrolling',
          items: [
            'catalog/scrolling/listview',
            'catalog/scrolling/scrollview',
          ],
        },
        {
          type: 'category',
          label: 'Feedback',
          items: [
            'catalog/feedback/dialog',
            'catalog/feedback/progress-indicators',
            'catalog/feedback/error-boundary',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        description: 'API documentation generated from Go source code.',
      },
      items: [
        {type: 'autogenerated', dirName: 'api'},
      ],
    },
  ],
};

export default sidebars;
