// Code generated by Drift plugin pipeline. DO NOT EDIT.
package com.drift.runner

object DriftPluginRegistrant {
    /** Creates one instance of every configured plugin, in drift.yaml order. */
    fun makePlugins(): List<DriftPlugin> = listOf(
    )
}
